# Generated by Django 3.2.7 on 2021-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateField(auto_now=True),
        ),
    ]
